[package]
name = "dirmarks"
version = "0.2.0"
authors = ["Luku <luku.3659@gmail.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.5", features = ["sqlite"] }
prettytable-rs = "0.8.0"
structopt = "0.3.21"
colored = "2.0.0"
anyhow = "1.0.38"
thiserror = "1.0.23"
derive_more = "0.99.11"
once_cell = "1.5.2"
dotenv = "0.15.0"
env_logger = "0.8.2"
log = "0.4.14"
termion = "1.5.6"
serde = { version = "1.0.123", features = ["derive"] }
config = "0.10.1"
smart-default = "0.6.0"
